# Generated by Django 6.1.1 on 2026-09-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("valid_rows", models.IntegerField(default=0)),
                ("duplicate_rows", models.IntegerField(default=0)),
                ("invalid_rows", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "normalized_company_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("website", models.URLField(blank=True, max_length=255)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("employees", models.IntegerField(blank=True, null=True)),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("technologies", models.JSONField(default=list)),
                ("hiring", models.BooleanField(default=False)),
                ("employee_growth", models.FloatField(blank=True, null=True)),
                ("funding_date", models.DateField(blank=True, null=True)),
                ("data_quality_score", models.IntegerField(default=0)),
                ("lead_score", models.IntegerField(default=0)),
                ("priority", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("normalized_title", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="leads.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.IntegerField()),
                ("industry_score", models.IntegerField()),
                ("employee_score", models.IntegerField()),
                ("revenue_score", models.IntegerField()),
                ("geography_score", models.IntegerField()),
                ("technology_score", models.IntegerField()),
                ("signal_score", models.IntegerField()),
                ("persona_score", models.IntegerField()),
                ("data_quality_score", models.IntegerField()),
                ("explanation", models.TextField(blank=True)),
                ("recommended_action", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_detail",
                        to="leads.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("value", models.JSONField(default=dict)),
                ("confidence", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="leads.lead",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["project", "lead_score"], name="leads_lead_project_0db6e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["project", "priority"], name="leads_lead_project_5011fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["project", "industry"], name="leads_lead_project_1789be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["project", "country"], name="leads_lead_project_5ea92d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["normalized_company_name"], name="leads_lead_normali_a85e38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["website"], name="leads_lead_website_91f024_idx"
            ),
        ),
    ]
